//
//  OptionRuleUsage.swift
//  SwiftFormatRuleStudio
//

import Foundation

/// Which SwiftFormat rule(s) consume a given option.
///
/// SwiftFormat options *tune* rules (e.g. `--self` drives `redundantSelf`), and
/// an option is a no-op unless its rule is enabled. This is a curated inverse of
/// every rule's `--ruleinfo` "Options:" section (SwiftFormat 0.61.x). In that
/// version all 124 options map to at least one rule (3 map to two); the
/// `OptionRuleUsageTests` integration test validates the table against the live
/// catalog so drift fails loudly.
public enum OptionRuleUsage {
    /// The rule(s) that consume the option with the given key (the `--name`
    /// without leading dashes). Empty if the option is unknown / unattributed.
    nonisolated public static func rules(forOptionKey key: String) -> [String] {
        rulesByOptionKey[key] ?? []
    }

    nonisolated static let rulesByOptionKey: [String: [String]] = [
        "acronyms": ["acronyms"],
        "allman": ["braces"],
        "allow-partial-wrapping": ["wrapArguments"],
        "anonymous-for-each": ["preferForLoop"],
        "asset-literals": ["wrap"],
        "async-capturing": ["hoistAwait"],
        "before-marks": ["organizeDeclarations"],
        "binary-grouping": ["numberFormatting"],
        "blank-line-after-switch-case": ["blankLineAfterSwitchCase"],
        "call-site-paren": ["wrapArguments"],
        "category-mark": ["organizeDeclarations"],
        "class-threshold": ["organizeDeclarations"],
        "closing-paren": ["wrapArguments"],
        "closure-void": ["redundantVoidReturnType"],
        "complex-attributes": ["wrapAttributes"],
        "computed-var-attributes": ["wrapAttributes"],
        "conditional-assignment": ["conditionalAssignment"],
        "date-format": ["fileHeader"],
        "decimal-grouping": ["numberFormatting"],
        "default-test-suite-attributes": ["preferSwiftTesting"],
        "doc-comments": ["docComments"],
        "else-position": ["elseOnSameLine"],
        "empty-braces": ["emptyBraces"],
        "enum-namespaces": ["enumNamespaces"],
        "enum-threshold": ["organizeDeclarations"],
        "equatable-macro": ["redundantEquatable"],
        "exponent-case": ["numberFormatting"],
        "exponent-grouping": ["numberFormatting"],
        "extension-acl": ["extensionAccessControl"],
        "extension-mark": ["markTypes"],
        "extension-threshold": ["organizeDeclarations"],
        "file-macro": ["fileMacro"],
        "fraction-grouping": ["numberFormatting"],
        "func-attributes": ["wrapAttributes"],
        "generic-types": ["genericExtensions"],
        "group-blank-lines": ["organizeDeclarations"],
        "grouped-extension": ["markTypes"],
        "guard-else": ["elseOnSameLine"],
        "header": ["fileHeader"],
        "hex-grouping": ["numberFormatting"],
        "hex-literal-case": ["numberFormatting"],
        "ifdef": ["indent"],
        "import-grouping": ["sortImports"],
        "indent": ["indent"],
        "indent-case": ["indent"],
        "indent-strings": ["indent"],
        "inferred-types": ["propertyTypes"],
        "init-coder-nil": ["initCoderUnavailable"],
        "lifecycle": ["organizeDeclarations"],
        "line-after-marks": ["blankLinesAroundMark"],
        "line-between-guards": ["blankLinesAfterGuardStatements"],
        "linebreaks": ["linebreaks"],
        "mark-categories": ["organizeDeclarations"],
        "mark-class-threshold": ["organizeDeclarations"],
        "mark-enum-threshold": ["organizeDeclarations"],
        "mark-extension-threshold": ["organizeDeclarations"],
        "mark-extensions": ["markTypes"],
        "mark-struct-threshold": ["organizeDeclarations"],
        "mark-types": ["markTypes"],
        "max-width": ["wrap"],
        "modifier-order": ["modifierOrder"],
        "never-trailing": ["trailingClosures"],
        "nil-init": ["redundantNilInit"],
        "no-space-operators": ["spaceAroundOperators"],
        "no-wrap-operators": ["wrap"],
        "non-complex-attributes": ["wrapAttributes"],
        "octal-grouping": ["numberFormatting"],
        "operator-func": ["spaceAroundOperators"],
        "organization-mode": ["organizeDeclarations"],
        "organize-types": ["organizeDeclarations"],
        "pattern-let": ["hoistPatternLet"],
        "prefer-synthesized-init-for-internal-structs": ["redundantMemberwiseInit"],
        "preserve-acronyms": ["acronyms"],
        "preserve-decls": ["unusedPrivateDeclarations"],
        "preserved-property-types": ["propertyTypes"],
        "property-types": ["propertyTypes", "redundantType"],
        "ranges": ["spaceAroundOperators"],
        "redundant-async": ["redundantAsync"],
        "redundant-throws": ["redundantThrows"],
        "self": ["redundantSelf"],
        "self-required": ["redundantSelf"],
        "semicolons": ["semicolons"],
        "short-optionals": ["typeSugar"],
        "single-line-for-each": ["preferForLoop"],
        "smart-tabs": ["indent"],
        "some-any": ["opaqueGenericParameters"],
        "sort-swiftui-properties": ["organizeDeclarations"],
        "sorted-patterns": ["sortDeclarations"],
        "stored-var-attributes": ["wrapAttributes"],
        "strip-unused-args": ["unusedArguments"],
        "struct-threshold": ["organizeDeclarations"],
        "suite-name-format": ["swiftTestingTestCaseNames"],
        "tab-width": ["indent"],
        "test-case-access-control": ["testSuiteAccessControl"],
        "test-case-name-format": ["swiftTestingTestCaseNames"],
        "throw-capturing": ["hoistTry"],
        "timezone": ["fileHeader"],
        "trailing-closures": ["trailingClosures"],
        "trailing-commas": ["trailingCommas"],
        "trim-whitespace": ["trailingSpace"],
        "type-attributes": ["wrapAttributes"],
        "type-blank-lines": ["blankLinesAtEndOfScope", "blankLinesAtStartOfScope"],
        "type-body-marks": ["organizeDeclarations"],
        "type-delimiter": ["spaceAroundOperators"],
        "type-mark": ["markTypes"],
        "type-marks": ["organizeDeclarations"],
        "type-order": ["organizeDeclarations"],
        "url-macro": ["urlMacro"],
        "visibility-marks": ["organizeDeclarations"],
        "visibility-order": ["organizeDeclarations"],
        "void-type": ["void"],
        "wrap-arguments": ["wrapArguments"],
        "wrap-collections": ["wrapArguments"],
        "wrap-conditions": ["wrapArguments"],
        "wrap-effects": ["wrapArguments"],
        "wrap-enum-cases": ["wrapEnumCases"],
        "wrap-parameters": ["wrapArguments"],
        "wrap-return-type": ["wrapArguments"],
        "wrap-string-interpolation": ["wrap", "wrapArguments"],
        "wrap-ternary": ["wrap"],
        "wrap-type-aliases": ["wrapArguments"],
        "xcode-indentation": ["indent"],
        "xctest-symbols": ["preferSwiftTesting"],
        "yoda-swap": ["yodaConditions"]
    ]
}
