//
//  ImpactReportExporter.swift
//  SwiftFormatRuleStudio
//

import Foundation
import LintStudioCore

/// Output formats for an exported impact report.
public enum ImpactExportFormat: String, CaseIterable, Sendable, Identifiable {
    case csv
    case html

    public var id: String { rawValue }
    /// File extension (without the dot).
    public var fileExtension: String { rawValue }
    /// Display name, e.g. `"CSV"`.
    public var displayName: String { rawValue.uppercased() }
}

/// Renders an `ImpactReport` to CSV or HTML, reusing LintStudioCore's escaping
/// and HTML template helpers.
public enum ImpactReportExporter {
    /// Exports the report in the given format. `timestamp` is supplied by the
    /// caller (Core stays free of `Date.now` for testability).
    public static func export(
        _ report: ImpactReport,
        as format: ImpactExportFormat,
        workspaceName: String,
        timestamp: String
    ) -> String {
        switch format {
        case .csv: csv(report)
        case .html: html(report, workspaceName: workspaceName, timestamp: timestamp)
        }
    }

    // MARK: - CSV

    private static func csv(_ report: ImpactReport) -> String {
        var lines = ["Rule,Files,Findings"]
        for impact in report.ruleImpacts {
            let rule = CSVEscaping.escape(impact.ruleID)
            lines.append("\(rule),\(impact.fileCount),\(impact.findingCount)")
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - HTML

    private static func html(_ report: ImpactReport, workspaceName: String, timestamp: String) -> String {
        let rows = report.ruleImpacts.map { impact in
            """
            <tr>
              <td><code>\(HTMLEscaping.escape(impact.ruleID))</code></td>
              <td>\(impact.fileCount)</td>
              <td>\(impact.findingCount)</td>
            </tr>
            """
        }
        .joined(separator: "\n")

        let body = """
        <p>\(report.ruleImpacts.count) rules · \(report.filesAffected) files affected · \
        \(report.totalFindings) findings</p>
        <table>
          <thead><tr><th>Rule</th><th>Files</th><th>Findings</th></tr></thead>
          <tbody>
        \(rows)
          </tbody>
        </table>
        """

        return HTMLReportTemplate.wrapInHTML(
            title: "SwiftFormat impact — \(workspaceName)",
            timestamp: timestamp,
            body: body,
            footerText: "Generated by SwiftFormat Rule Studio"
        )
    }
}
