#!/usr/bin/env python3
"""Generate CuratedLiveExample+Generated.swift from the CuratedExamples/*.md files.

Each markdown file (one per rule, named <ruleName>.md) holds optional prose plus a
single ```swift fenced block — the curated "before" snippet. This script extracts
that block from every file and emits one compiled Swift dictionary. The markdown
files are the human source of truth; the generated file is a build artifact
(SwiftLint-excluded) and should not be hand-edited.

Run from the repo root:  python3 Scripts/generate_curated_examples.py
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MD_DIR = REPO / "SwiftFormatRuleStudioCore" / "CuratedExamples"
OUT = (REPO / "SwiftFormatRuleStudioCore" / "Sources" / "SwiftFormatRuleStudioCore"
       / "Parsing" / "CuratedLiveExample+Generated.swift")

FENCE = re.compile(r"```swift\n(.*?)\n```", re.DOTALL)


def swift_literal(text: str) -> str:
    """A single-line, fully-escaped Swift string literal (avoids multiline/interp pitfalls)."""
    escaped = (text.replace("\\", "\\\\")
                   .replace("\"", "\\\"")
                   .replace("\t", "\\t")
                   .replace("\r", "\\r")
                   .replace("\n", "\\n"))
    return f"\"{escaped}\""


def main() -> int:
    files = sorted(MD_DIR.glob("*.md"))
    if not files:
        print(f"error: no .md files in {MD_DIR}", file=sys.stderr)
        return 1

    def note_of(text: str) -> str:
        """Prose body of a markdown file with the leading `# title` heading removed."""
        lines = [ln for ln in text.splitlines() if not ln.startswith("# ")]
        return " ".join(ln.strip() for ln in lines if ln.strip())

    snippets, notes = [], []
    for path in files:
        rule = path.stem
        match = FENCE.search(path.read_text())
        if match:
            snippet = match.group(1).rstrip("\n")
            snippets.append(f"        {swift_literal(rule)}: {swift_literal(snippet)},")
        else:
            # A snippet-less file is an "unavailable note": the rule acts on a
            # file-level/invisible aspect a code diff can't show.
            note = note_of(path.read_text())
            if note:
                notes.append(f"        {swift_literal(rule)}: {swift_literal(note)},")
            else:
                print(f"warning: {path.name} has neither a ```swift block nor a note", file=sys.stderr)

    snippet_body = "\n".join(snippets)
    note_body = "\n".join(notes)
    OUT.write_text(
        "//\n"
        "//  CuratedLiveExample+Generated.swift\n"
        "//  SwiftFormatRuleStudio\n"
        "//\n"
        "//  GENERATED by Scripts/generate_curated_examples.py — do not edit by hand.\n"
        "//  Source of truth: SwiftFormatRuleStudioCore/CuratedExamples/<rule>.md\n"
        "//\n\n"
        "import Foundation\n\n"
        "extension CuratedLiveExample {\n"
        "    static let generatedSnippets: [String: String] = [\n"
        f"{snippet_body}\n"
        "    ]\n\n"
        "    static let generatedNotes: [String: String] = [\n"
        f"{note_body}\n"
        "    ]\n"
        "}\n"
    )
    print(f"generated {OUT.relative_to(REPO)} with {len(snippets)} snippets, {len(notes)} notes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
