#!/usr/bin/env python3
"""Generate CuratedLiveExample+Generated.swift from the CuratedExamples/*.md files.

Each markdown file (one per rule, named <ruleName>.md) holds optional prose plus a
single ```swift fenced block — the curated "before" snippet. This script extracts
that block from every file and emits one compiled Swift dictionary. The markdown
files are the human source of truth; the generated file is a build artifact
(SwiftLint-excluded) and should not be hand-edited.

Run from the repo root:  python3 Scripts/generate_curated_examples.py
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MD_DIR = REPO / "SwiftFormatRuleStudioCore" / "CuratedExamples"
OUT = (REPO / "SwiftFormatRuleStudioCore" / "Sources" / "SwiftFormatRuleStudioCore"
       / "Parsing" / "CuratedLiveExample+Generated.swift")

FENCE = re.compile(r"```swift\n(.*?)\n```", re.DOTALL)


def swift_literal(text: str) -> str:
    """A single-line, fully-escaped Swift string literal (avoids multiline/interp pitfalls)."""
    escaped = (text.replace("\\", "\\\\")
                   .replace("\"", "\\\"")
                   .replace("\t", "\\t")
                   .replace("\r", "\\r")
                   .replace("\n", "\\n"))
    return f"\"{escaped}\""


def main() -> int:
    files = sorted(MD_DIR.glob("*.md"))
    if not files:
        print(f"error: no .md files in {MD_DIR}", file=sys.stderr)
        return 1

    def prose(text: str) -> str:
        """The rationale prose: everything before the ```swift fence, minus the
        `# title` heading, collapsed to one line. For a snippet-less file this is
        the whole body."""
        before = text.split("```swift", 1)[0]
        lines = [ln.strip() for ln in before.splitlines() if ln.strip() and not ln.startswith("# ")]
        return " ".join(lines)

    snippets, notes, hints = [], [], []
    for path in files:
        rule = path.stem
        text = path.read_text()
        match = FENCE.search(text)
        body = prose(text)
        if match:
            snippet = match.group(1).rstrip("\n")
            snippets.append(f"        {swift_literal(rule)}: {swift_literal(snippet)},")
            # Prose above a snippet becomes a contextual hint shown in the app.
            if body:
                hints.append(f"        {swift_literal(rule)}: {swift_literal(body)},")
        elif body:
            # A snippet-less file is an "unavailable note": the rule acts on a
            # file-level/invisible aspect a code diff can't show.
            notes.append(f"        {swift_literal(rule)}: {swift_literal(body)},")
        else:
            print(f"warning: {path.name} has neither a ```swift block nor prose", file=sys.stderr)

    def section(name, rows):
        return f"    static let {name}: [String: String] = [\n" + "\n".join(rows) + "\n    ]\n"

    OUT.write_text(
        "//\n"
        "//  CuratedLiveExample+Generated.swift\n"
        "//  SwiftFormatRuleStudio\n"
        "//\n"
        "//  GENERATED by Scripts/generate_curated_examples.py — do not edit by hand.\n"
        "//  Source of truth: SwiftFormatRuleStudioCore/CuratedExamples/<rule>.md\n"
        "//\n\n"
        "import Foundation\n\n"
        "extension CuratedLiveExample {\n"
        + section("generatedSnippets", snippets) + "\n"
        + section("generatedNotes", notes) + "\n"
        + section("generatedHints", hints)
        + "}\n"
    )
    print(f"generated {OUT.relative_to(REPO)}: {len(snippets)} snippets, {len(notes)} notes, {len(hints)} hints")
    return 0


if __name__ == "__main__":
    sys.exit(main())
