#!/usr/bin/env python3
"""Generate the per-version rule catalog the upgrade digest diffs against.

For each anchor version, downloads that release's `swiftformat` binary, asks it
for `--rules`, and writes the resulting name sets into a generated Swift table.

    Scripts/generate_rule_history.py            # regenerate from ANCHORS
    Scripts/generate_rule_history.py 0.61.1 …   # or an explicit list

Why downloaded binaries rather than the linked library: the app links exactly one
SwiftFormat (`exact: "0.62.1"`), and the whole point here is what *older* versions
knew about. Running each release once, at generation time, keeps that out of the
shipping app — see docs/version-upgrade-diff-scope.md §2.
"""

import io
import json
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
import zipfile
from pathlib import Path

# The last release of each recent minor series. These are the versions a user can
# say they are upgrading *from*; the set is deliberately small and explicit,
# because "any version" is not on offer (scope doc §6).
ANCHORS = ["0.55.6", "0.56.4", "0.57.2", "0.58.7", "0.59.1", "0.60.1", "0.61.1"]

RELEASE_URL = "https://github.com/nicklockwood/SwiftFormat/releases/download/{v}/swiftformat.zip"
OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "SwiftFormatRuleStudioCore/Sources/SwiftFormatRuleStudioCore/Models/RuleHistory+Generated.swift"
)

RULE_LINE = re.compile(r"^\s*(\w+)(\s+\(disabled\))?\s*$")


def rules_for(version: str, workdir: Path) -> list[str]:
    """Download one release and return the rule names it ships."""
    url = RELEASE_URL.format(v=version)
    print(f"  {version}: downloading", flush=True)
    with urllib.request.urlopen(url) as response:
        payload = response.read()

    target = workdir / version
    target.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        archive.extractall(target)

    binary = next(p for p in target.rglob("swiftformat") if p.is_file())
    binary.chmod(0o755)
    output = subprocess.run(
        [str(binary), "--rules"], capture_output=True, text=True, check=True
    ).stdout

    names = []
    for line in output.splitlines():
        match = RULE_LINE.match(line)
        if match:
            names.append(match.group(1))
    if not names:
        raise SystemExit(f"{version}: --rules produced nothing parseable")
    print(f"  {version}: {len(names)} rules", flush=True)
    return sorted(names)


def main() -> None:
    versions = sys.argv[1:] or ANCHORS
    workdir = Path(tempfile.mkdtemp(prefix="sfrs-rule-history-"))
    try:
        catalogs = {version: rules_for(version, workdir) for version in versions}
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    lines = [
        "//",
        "//  RuleHistory+Generated.swift",
        "//  SwiftFormatRuleStudio",
        "//",
        "//  GENERATED by Scripts/generate_rule_history.py — do not edit by hand.",
        "//  Source of truth: the `--rules` output of each released SwiftFormat binary.",
        "//",
        "",
        "extension RuleHistory {",
        "    /// Rule names shipped by each anchor version, newest first.",
        "    ///",
        "    /// `nonisolated` because the package defaults to `MainActor` isolation and",
        "    /// `RuleHistory` is read from wherever a scan is being assembled.",
        "    nonisolated static let generatedCatalogs: [String: Set<String>] = [",
    ]
    for version in sorted(catalogs, reverse=True):
        names = ", ".join(f'"{n}"' for n in catalogs[version])
        lines.append(f'        "{version}": [{names}],')
    lines += ["    ]", "}", ""]

    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(Path.cwd())} ({len(catalogs)} versions)")


if __name__ == "__main__":
    main()
