//
//  ImpactReportExporterTests.swift
//  SwiftFormatRuleStudioCoreTests
//

@testable import SwiftFormatRuleStudioCore
import Testing

@Suite("ImpactReportExporter")
struct ImpactReportExporterTests {
    private static let report = ImpactReport(
        filesAffected: 3,
        totalFindings: 5,
        ruleImpacts: [
            RuleImpact(ruleID: "indent", fileCount: 2, findingCount: 3),
            RuleImpact(ruleID: "spaceAroundOperators", fileCount: 1, findingCount: 2)
        ]
    )

    @Test("CSV has a header and one row per rule")
    func csv() {
        let csv = ImpactReportExporter.export(
            Self.report, as: .csv, workspaceName: "Demo", timestamp: "2026-06-04"
        )
        let lines = csv.split(separator: "\n")
        #expect(lines.first == "Rule,Files,Findings")
        #expect(lines.count == 3)
        #expect(lines.contains("indent,2,3"))
        #expect(lines.contains("spaceAroundOperators,1,2"))
    }

    @Test("HTML wraps the report in a full document")
    func html() {
        let html = ImpactReportExporter.export(
            Self.report, as: .html, workspaceName: "Demo", timestamp: "2026-06-04"
        )
        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("SwiftFormat impact — Demo"))
        #expect(html.contains("<code>indent</code>"))
        #expect(html.contains("Generated by SwiftFormat Rule Studio"))
    }

    @Test("Export format metadata")
    func formats() {
        #expect(AuditExportFormat.csv.fileExtension == "csv")
        #expect(AuditExportFormat.html.displayName == "HTML")
        #expect(AuditExportFormat.allCases.count == 2)
    }
}
